#### CGF Get login token ###
- name: "CGF - Check existance token {{ request_tokenname }}"
  uri:
    url: "{{ request_url }}/rest/config/v1/box/admins/{{ request_user }}/tokens/{{ request_tokenname }}"
    method: GET
    force_basic_auth: yes
    user: "{{ request_user }}"
    password: "{{ request_password }}"
    headers:
      Content-Type: "application/json"
    status_code: 200
    validate_certs: False
    return_content: yes
  register: result
  ignore_errors: True
  until: result.status != -1

#- debug:
#    msg: "CGF API result: {{ result }}"

- set_fact:
    cgf_access_token: "{{ result.json.token }}"
  when: result is succeeded

- name: "CGF - Get login token"
  when: result is failed
  uri:
    url: "{{ request_url }}/rest/config/v1/box/admins/{{ request_user }}/tokens"
    method: POST
    user: "{{ request_user }}"
    password: "{{ request_password }}"
    body: '{ "name": "{{ request_tokenname }}", "rcsMessage": "Quickstart demo", "ttl": 30 }'
    body_format: json
    timeout: 60
    headers:
      Content-Type: "application/json"
    validate_certs: False
  register: result
  until: result.status != -1

#- debug:
#    msg: "CGF API token: {{ result }}"

- pause:
    prompt: "Calm down young padawan ..."
    seconds: 1 
  when: "'skipped' not in result"

- set_fact:
    cgf_access_token: "{{ result.json.token }}"
  when: "'skipped' not in result"
