#### CGF Delete login token ###
- name: "CGF - Delete login token"
  uri:
    url: "{{ request_url }}/rest/config/v1/box/admins/{{ request_user }}/tokens/{{ request_tokenname }}"
    method: DELETE
    timeout: 60
    headers:
      Content-Type: "application/json"
      X-API-Token: "{{ request_token }}"
    status_code: 204
    validate_certs: False
  register: result
  until: result.status != -1
